### ISSUE TITLE
Errors in module.json

### ISSUE THREAD

**Issue by IzzySoft** [Minionguyjpro/NovaInstaller#20]
Your current `module.json` has some syntax errors, and does not match the `module.prop`:

```json
{
    "version": v1.1.1,
    "versionCode": 1.1.1,
```

should rather read

```json
{
    "version": "v1.1.1",
    "versionCode": 111
```

(`versioncode` must be an integer, and `version` an explicit string). Could you please fix that, so the file can be used as a proper `update.json`? Thanks in advance!

**Comment by IzzySoft** [comment]
@Minionguyjpro any word?

**Comment by Minionguyjpro** [comment]
Hello,

Oh sorry, did not really mind some GitHub stuff for a long time. This also declares why the updater for the Magisk module might not work. Let me fix it

**Comment by Minionguyjpro** [comment]
This issue has been fixed. I will change the license to Apache.

**Comment by IzzySoft** [comment]
Thanks! So the remaining question is whether NovaLauncher itself is FOSS (as you include its APK). Background is adding your module to [my repo](https://apt.izzysoft.de/magisk) which is about FOSS modules. If Nova is FOSS, all is fine. If not, I'd need to clearly mark that (like adding the `NonFreeComp` which makes it transparent the module contains non-free components (here: Nova).

Maybe one further question: I see you've automated updating the APK here. If I'd use your module, will that automatically pull the new APK, or would the module need to be updated – or which way is it supposed to work? I guess the module is thought for the initial "systemization", and then updates are the same way as with other system apps until some other updates are pushed for the module – but I'd rather like to know than to guess :see_no_evil:

**Comment by Minionguyjpro** [comment]
> Thanks! So the remaining question is whether NovaLauncher itself is FOSS (as you include its APK). Background is adding your module to [my repo](https://apt.izzysoft.de/magisk) which is about FOSS modules. If Nova is FOSS, all is fine. If not, I'd need to clearly mark that (like adding the `NonFreeComp` which makes it transparent the module contains non-free components (here: Nova).
> 
> Maybe one further question: I see you've automated updating the APK here. If I'd use your module, will that automatically pull the new APK, or would the module need to be updated – or which way is it supposed to work? I guess the module is thought for the initial "systemization", and then updates are the same way as with other system apps until some other updates are pushed for the module – but I'd rather like to know than to guess 🙈

I have set it to the Apache 2.0 license.

**Comment by IzzySoft** [comment]
So Nova itself is using Apache license too?

**Comment by Minionguyjpro** [comment]
> So Nova itself is using Apache license too?

Actually not sure, but online I found out that the most part of Android app code is primarily Apache 2.0. However, where would I find which license Nova uses?

**Comment by IzzySoft** [comment]
> However, where would I find which license Nova uses?

Exactly that was my problem :see_no_evil: Nevermind, as no source was found (I've checked their website and their FAQ) we must assume it's proprietary. So I've just added your module attaching Apache-2.0 and marking it with the NonFreeComp anti-feature (ie. transparently communicating it contains Non Free Components, which is the Nova APK). Should the Nova folks complain, they can point us to source & license then :smile:

Thanks for your help and patience! I still wonder why the updater picked v1.1.1 while the `module.json` clearly states v1.1.2 and `latest` points there, too… 

    NovaInstaller: update to latest version: v1.1.1-111

Hm… maybe the `module.prop` in the ZIP attached to the release was not updated? Bingo:

```ini
id=NovaInstaller
name=NovaInstaller
version=v1.1.1
versionCode=111
author=Minionguyjpro
description=Installs the Nova Launcher to '/system/app/' on Android.
updateJson=https://raw.githubusercontent.com/Minionguyjpro/NovaInstaller/main/module.json
```

So: back to the description of this issue I guess? :see_no_evil:

**Comment by Minionguyjpro** [comment]
> 

This is probably because version 1.1.1 had errors, so it won't update correctly. Starting v1.1.2, it should work with newer versions.

**Comment by Minionguyjpro** [comment]
> > However, where would I find which license Nova uses?
> 
> Exactly that was my problem 🙈 Nevermind, as no source was found (I've checked their website and their FAQ) we must assume it's proprietary. So I've just added your module attaching Apache-2.0 and marking it with the NonFreeComp anti-feature (ie. transparently communicating it contains Non Free Components, which is the Nova APK). Should the Nova folks complain, they can point us to source & license then 😄
> 
> Thanks for your help and patience! I still wonder why the updater picked v1.1.1 while the `module.json` clearly states v1.1.2 and `latest` points there, too…
> 
> ```
> NovaInstaller: update to latest version: v1.1.1-111
> ```
> 
> Hm… maybe the `module.prop` in the ZIP attached to the release was not updated? Bingo:
> 
> ```ini
> id=NovaInstaller
> name=NovaInstaller
> version=v1.1.1
> versionCode=111
> author=Minionguyjpro
> description=Installs the Nova Launcher to '/system/app/' on Android.
> updateJson=https://raw.githubusercontent.com/Minionguyjpro/NovaInstaller/main/module.json
> ```
> 
> So: back to the description of this issue I guess? 🙈

I think it does not care. It just tells the current version but not sure. Next release I also now made that it automatically ZIPs with the version in the ``module.prop`` being automatically set based on what is set in ``module.json``.

**Comment by IzzySoft** [comment]
> This is probably because version 1.1.1 had errors, so it won't update correctly.

That's from the `module.prop` in the archive attached to tag 1.1.2, so nothing to do with updates.

> I think it does not care. It just tells the current version but not sure.

Well, it results in updaters pulling the same version over and again, as locally it says 1.1.1 but there's a tag for 1.1.2 already :see_no_evil: But if the next release fixes that, that should be fine.

**Comment by Minionguyjpro** [comment]
> > This is probably because version 1.1.1 had errors, so it won't update correctly.
> 
> That's from the `module.prop` in the archive attached to tag 1.1.2, so nothing to do with updates.
> 
> > I think it does not care. It just tells the current version but not sure.
> 
> Well, it results in updaters pulling the same version over and again, as locally it says 1.1.1 but there's a tag for 1.1.2 already 🙈 But if the next release fixes that, that should be fine.

It would actually be better to update the version and make the release at the same time. But not really sure how to get started though. I think it would be possible with a workflow. Would you be able to help me with that?

**Comment by IzzySoft** [comment]
Sorry, I never played with Github workflows (or with GitLabs, or Codebergs), so unfortunately not.

**Comment by Minionguyjpro** [comment]
> Sorry, I never played with Github workflows (or with GitLabs, or Codebergs), so unfortunately not.

Okay. It isn't that hard though. I know there is an action to automatically make a release, but I do not want to make one after merging any PR into the ``main`` branch. This could be done by for example having a file, saying whether to make a release or not. Then the workflow runs the commands to check that, set it into a variable and run the make release section if the variable is set to 1 or true. Although I hoped there to be a better way.

**Comment by IzzySoft** [comment]
I'd base it on pushing a tag, if that's possible. A release would need a tag anyway, right? And one usually tags to mark a release.

**Comment by Minionguyjpro** [comment]
> I'd base it on pushing a tag, if that's possible. A release would need a tag anyway, right? And one usually tags to mark a release.

Yes
