### ISSUE TITLE
Update to 1.1.2 issue

### ISSUE THREAD

**Issue by Bozinsky2023** [Minionguyjpro/NovaInstaller#28]
Installed latest version
tried both ways to install procedure :magisk/TWRP
at boot magisk always shows version 1.1.1 and requires to update.
Update process shows version 1.1.2 was installed
After reboot, version is still 1.1.1 and - again - requires to update to 1.1.2

Opened Module.prop and it reports version 1.1.1

**Comment by Minionguyjpro** [comment]
I made version 1.1.3. Try updating again now and it should find version 1.1.3. Does it work now?

**Comment by Bozinsky2023** [comment]
Update to 1.1.3 went successfully.
Installed module reports 1.1.3
Thanks for your fast replay

**Comment by Minionguyjpro** [comment]
> Update to 1.1.3 went successfully. Installed module reports 1.1.3 Thanks for your fast replay

No problem! I have holiday now and much time to do some stuff.
